config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint_fix
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/jsc-jupyter/jupyterlab-data-mount:
      branch: main
      repo: https://github.com/jsc-jupyter/jupyterlab-data-mount.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/jsc-jupyter/jupyterlab-data-mount git:
        commands:
        - /usr/bin/env sh .sqa/script.daffodil_mature_echidna.sh
        container: qc.acc_lapis_sincere_impala
  QC.Doc:
    repos:
      github.com/jsc-jupyter/jupyterlab-data-mount find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.fog_reserved_hornbill.sh
        container: qc.doc_tundra_ambitious_heron
      github.com/jsc-jupyter/jupyterlab-data-mount git:
        commands:
        - /usr/bin/env sh .sqa/script.kiwi_stubborn_warthog.sh
        container: qc.doc_lapis_confident_hedgehog
      github.com/jsc-jupyter/jupyterlab-data-mount markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lapis_amiable_fox.sh
        container: qc.doc_horizon_optimistic_fox
  QC.Lic:
    repos:
      github.com/jsc-jupyter/jupyterlab-data-mount licensee:
        commands:
        - /usr/bin/env sh .sqa/script.thistle_bold_whale.sh
        container: qc.lic_vermilion_philosophical_wolf
  QC.Sec:
    repos:
      github.com/jsc-jupyter/jupyterlab-data-mount bandit:
        commands:
        - /usr/bin/env sh .sqa/script.ruby_meticulous_phoenix.sh
        container: qc.sec_forest_organized_bullfrog
  QC.Sty:
    repos:
      github.com/jsc-jupyter/jupyterlab-data-mount flake8:
        commands:
        - /usr/bin/env sh .sqa/script.ruby_insightful_lobster.sh
        container: qc.sty_malachite_smart_mongoose
      github.com/jsc-jupyter/jupyterlab-data-mount jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.ash_wise_owl.sh
        container: qc.sty_teal_mysterious_cassowary
  QC.Uni:
    repos:
      github.com/jsc-jupyter/jupyterlab-data-mount pytest:
        commands:
        - /usr/bin/env sh .sqa/script.pearl_motivated_swan.sh
        container: qc.uni_mulberry_energetic_serval
  QC.Ver:
    repos:
      github.com/jsc-jupyter/jupyterlab-data-mount get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.heather_peppy_shark.sh
        container: qc.ver_fandango_mysterious_giraffe
timeout: 5400
